package main;

public enum Colors {

	NEGRO("NEGRO"), BLANCO("BLANCO"), ROJO("ROJO"), AZUL("AZUL"), AMARILLO("AMARILLO"), VERDE("VERDE"), ROSA("ROSA"),
	VIOLETA("VIOLETA"), GRIS("GRIS"), CYAN("CYAN"), AZUL_OSCURO("AZUL OSCURO"), AZUL_CLARO("AZUL CLARO")

	, PURPURA("PÃšRPURA"), MAGENTA("MAGENTA"), PLATA("PLATA"), NARANJA("NARANJA"), CASTAÑO("CASTAÑO"), MARRON("MARRÃ“N"),
	VERDE_BOTELLA("VERDE BOTELLA"), OLIVA("OLIVA"), AQUAMARINE("AGUA"), ORO("ORO"), DARK_ORANGE("NARANJA OSCURO"),
	ORO_VIEJO("ORO VIEJO"), CHOCOLATE("CHOCOLATE"), ORO_ROTO("ORO ROTO"), TURQUESA("TURQUESA"), TEAL("VERDE AZULADO"),
	SEAGREEN("MAR VERDE"), CAMUFLAJE("CAMUFLAJE"), BRONCE("BRONCE"), VAINILLA("VAINILLA");

	public final String label;

	Colors(final String text) {
		this.label = text;
	}

	@Override

	public String toString() {
		return label;
	}

}
